In [1]:
import numpy as np

import math
from entities import Board
from learning import State, Action, MonteCarloEstimation
import random

np.random.seed(28)
random.seed(28)


In [6]:
a = np.random.randint(0, 3, (3,3))
b = np.random.randint(0, 3, (3,3))
bool(np.all(a == b))

False

In [10]:
a = np.random.randint(low=0, high=4, size=(3,3))
print(a)
np.count_nonzero(a == 2)

[[3 0 2]
 [1 2 0]
 [0 2 3]]


np.int64(3)